# Generated by Django 5.2.12 on 2026-03-18 01:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def backfill_client_owned_categories(apps, schema_editor):
    EventCategory = apps.get_model("planner", "EventCategory")
    Event = apps.get_model("planner", "Event")

    for category in EventCategory.objects.all().order_by("id"):
        client_ids = list(
            Event.objects.filter(category_id=category.id).values_list("client_id", flat=True).distinct().order_by("client_id")
        )

        if not client_ids:
            continue

        primary_client_id = client_ids[0]
        category.client_id = primary_client_id
        category.save(update_fields=["client"])

        for client_id in client_ids[1:]:
            clone = EventCategory.objects.create(
                client_id=client_id,
                name=category.name,
                color=category.color,
            )
            Event.objects.filter(category_id=category.id, client_id=client_id).update(category_id=clone.id)


class Migration(migrations.Migration):

    dependencies = [
        ('planner', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='eventcategory',
            name='client',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='event_categories', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='eventcategory',
            name='color',
            field=models.CharField(choices=[('rose', 'Rose'), ('orange', 'Orange'), ('amber', 'Amber'), ('emerald', 'Emerald'), ('sky', 'Sky'), ('indigo', 'Indigo')], default='emerald', max_length=20),
        ),
        migrations.AlterField(
            model_name='eventcategory',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.RunPython(backfill_client_owned_categories, migrations.RunPython.noop),
        migrations.AddConstraint(
            model_name='eventcategory',
            constraint=models.UniqueConstraint(fields=('client', 'name'), name='unique_event_category_name_per_client'),
        ),
    ]
