# Generated by Django 5.2.12 on 2026-03-18 02:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planner', '0002_eventcategory_client_eventcategory_color_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='recurrence_type',
            field=models.CharField(choices=[('none', 'Does not repeat'), ('daily', 'Daily'), ('weekly', 'Weekly'), ('monthly', 'Monthly')], default='none', max_length=20),
        ),
        migrations.AddField(
            model_name='event',
            name='recurrence_until',
            field=models.DateField(blank=True, null=True),
        ),
    ]
